### ISSUE TITLE
[Migration] Migrate erc-2981 Smart Contract from Cairo 0.10 to Cairo 1

### ISSUE THREAD

**Issue by cloudvenger** [carbonable-labs/cairo-erc-2981#3]
# Description

The [ERC-2981](https://eips.ethereum.org/EIPS/eip-2981) is writing in Cairo 0.10 and he is working. 

# Tasks

The Tasks are : 
- [ ] Migrate the `src/erc2981` from Cairo 0.10 to Cairo 1 (preset, constants, library)
- [ ] Migrate the tests
- [ ] Add tests to migrate an ERC-2981 Smart Contract from Cairo 0.10 to Cairo 1
